nginx:
  build: nginx/
  volumes:
    - /etc/letsencrypt/:/etc/letsencrypt
    - ./app:/www/app
  ports:
    - "80:80"
    - "443:443"
  links:
    - api

api:
  build: ./api
  hostname: localhost
  ports:
    - "3000:3000"
