nginx:
  build: ../nginx
  volumes:
    - /etc/letsencrypt/:/etc/letsencrypt
    - /root/dev/can-i-uber/build:/www/can-i-uber
    - ./app:/www/app
  ports:
    - "80:80"
    - "443:443"
  links:
    - freegeoip
    - api

freegeoip:
  build: ../freegeoip
  hostname: localhost
  ports:
    - "8080:8080"

api:
  build: ./api
  hostname: localhost
  ports:
    - "3000:3000"
